---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    boxes:
      - rockylinux9-aarch64
        #      - rockylinux9
    versions: {}

  tasks:

    - include_tasks: shared/build-a-box.yml
      with_items: "{{ boxes }}"
